# Generated by Django 5.1.1 on 2024-10-03 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChargePoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("charge_point_id", models.CharField(max_length=100, unique=True)),
                ("vendor", models.CharField(max_length=100)),
                ("model", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=50)),
                ("last_heartbeat", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("transaction_id", models.IntegerField(unique=True)),
                ("start_time", models.DateTimeField()),
                ("stop_time", models.DateTimeField(blank=True, null=True)),
                ("meter_start", models.IntegerField()),
                ("meter_stop", models.IntegerField(blank=True, null=True)),
                (
                    "charge_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="charging.chargepoint",
                    ),
                ),
            ],
        ),
    ]
